export {
  CATALOG_VERSION,
  GEOMETRY_FIELDS,
  type Catalog,
  type CatalogTool,
  type Facets,
  type GeometryField,
  type Provenance,
  type RangeAxis,
  type TermAxis,
  type ToolFamily,
  MATERIAL_GROUPS,
  type ToolType,
  type UnitSystem,
} from './types.js'
export {
  IngestError,
  ingest,
  type Ingested,
  type IngestNote,
  type Scrape,
  type ScrapedFamily,
  type ScrapedTool,
  type ScrapedUnit,
} from './ingest.js'
export {
  CatalogBuildError,
  buildCatalog,
  withDerived,
  undefinedGeometryCodes,
  type CatalogInput,
  type FamilyInput,
} from './build.js'
export { facetsFor } from './facets.js'
export {
  demandOf,
  demandsOf,
  fitAgainst,
  fitTools,
  toolsForFeatures,
  type DemandContext,
  type FeatureDemand,
  type FitFailure,
  type ToolFit,
} from './fit.js'
export {
  assembliesFor,
  canHold,
  colletFitsHolder,
  gripRanges,
  gripsAnyShank,
  gripsShank,
  holderTakesTool,
  maxStickout,
  minStickout,
  DEFAULT_STICKOUT_POLICY,
  defaultStickout,
  stickoutLimits,
  holdBand,
  type HoldBand,
  HELD_SHARE,
  withStickout,
  type Assembly,
  type Clamping,
  type Collet,
  type Contact,
  type GripRanges,
  type Holder,
  type StickoutLimits,
  type StickoutPolicy,
} from './toolholding.js'
export {
  NOT_MODELLED,
  assembliesForFeatures,
  assemblyAgainst,
  unholdableTools,
  type AssemblyFit,
} from './assembly-fit.js'
export {
  PASSES,
  mapTool,
  mappingFor,
  passProgress,
  planProgress,
  strayMappings,
  toolsInPlan,
  unmap,
  unmappedFeatures,
  type Mapping,
  type Pass,
  type PassProgress,
  type Plan,
} from './mapping.js'
export {
  NO_PREFERENCES,
  materialStanding,
  preferredFor,
  recommend,
  recommended,
  togglePreferred,
  type MaterialStanding,
  type Preferences,
  type Recommendation,
} from './preferences.js'
export {
  MILLING_FORMS,
  TOOL_FORMS,
  isToolForm,
  hasNeck,
  shankOf,
  type Shank,
  type ToolForm,
} from './forms.js'
export type { ToolInput } from './types.js'
export {
  clearance,
  NO_MARGINS,
  type Margins,
  describeCollision,
  heightAt,
  toolCollisions,
  toolSilhouette,
  type Clearance,
  type Collision,
  type Silhouette,
  type SilhouettePart,
} from './clearance.js'
export {
  assemblyOutline,
  materialProfile,
  type Outline,
  type Outlined,
  type OutlinePart,
  type OutlinePoint,
  type OutlineSegment,
} from './outline.js'
export { tightestGaps, wallFaceAt, type AxialGap, type Gap, type Gaps } from './gaps.js'
export {
  HOLDER_AXES,
  applicableFilters,
  axisConstrains,
  collapse,
  colletsFor,
  colletsForShank,
  compareHolders,
  holderFacet,
  holderCanTake,
  holderNeedsCollet,
  holdersFor,
  isOnSize,
  matchesFilters,
  seriesSize,
  type HolderAxis,
  type HolderFilters,
} from './assembly-picking.js'
export {
  axisApplies,
  buildParamNames,
  emptyBuildSelection,
  fromBuildParams,
  holderFiltersFrom,
  selectCollet,
  selectHolder,
  toBuildParams,
  toggleBuildTerm,
  withBuildStickout,
  writeBuildParams,
  type BuildSelection,
} from './assembly-selection.js'

export {
  sectionOutline,
  FLOOR_BAND,
  REACH,
  type FeatureSection,
  type Section,
  type SectionKind,
  type SectionPoint,
} from './section.js'
